[package]
name = "fast-woothee"
version = "0.2.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]
edition = "2021"

[lib]
name = "_woothee"
crate-type = ["cdylib"]

[dependencies]
woothee = "^0.10"

[dependencies.pyo3]
version = "0.25.0"
features = ["extension-module"]
